# render_map.py
"""
Render the output of cli_search.py on an interactive map (using Folium).
Shows:
 - Real location (red marker)
 - Dummy locations (blue markers)
 - Found places (green markers)
"""

import sys, json, webbrowser
from pathlib import Path
import folium

if len(sys.argv) < 2:
    print("Usage: python render_map.py places_output_<query>.json")
    sys.exit(1)

json_path = Path(sys.argv[1])
if not json_path.exists():
    print("❌ File not found:", json_path)
    sys.exit(1)

# Load the JSON file generated by cli_search.py
data = json.loads(json_path.read_text())

center = data.get("center", {})
lat, lon = center.get("lat"), center.get("lon")

# Create map centered on the real location
m = folium.Map(location=[lat, lon], zoom_start=13, tiles="OpenStreetMap")

# Add marker for the real location
folium.Marker(
    [lat, lon],
    popup="📍 Real Location",
    icon=folium.Icon(color="red", icon="user"),
).add_to(m)

# Add dummy markers
for d in data.get("dummies", []):
    folium.Marker(
        [d["lat"], d["lon"]],
        popup="🌀 Dummy Location",
        icon=folium.Icon(color="blue", icon="cloud"),
    ).add_to(m)

# Add found places (green markers)
for p in data.get("merged_places", []):
    popup_text = f"{p.get('name', 'Unknown')}<br>{p.get('address', '')}<br>⭐ {p.get('rating', 'N/A')}"
    folium.Marker(
        [p["lat"], p["lon"]],
        popup=popup_text,
        icon=folium.Icon(color="green", icon="ok-sign"),
    ).add_to(m)

# Save the map to an HTML file
map_file = json_path.stem + "_map.html"
m.save(map_file)
print(f"✅ Map saved to {map_file}")

# Open in browser automatically
webbrowser.open(map_file)
